name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 如果您的主分支名稱是 master，請改為 master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 預設編譯後的資料夾名稱
          branch: gh-pages # 這是 GitHub Actions 會自動幫您建立並推播編譯產物的分支
